"""Create User table

Revision ID: 82f709e667e6
Revises: 
Create Date: 2025-09-10 20:19:15.970842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f709e667e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('person_type', sa.String(length=20), nullable=False),
    sa.Column('nif', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('notification_address', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('cadastral_reference', sa.String(length=20), nullable=False),
    sa.Column('cadastral_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('cadastral_reference')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_value', sa.Float(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('grantor_id', sa.Integer(), nullable=True),
    sa.Column('grantee_id', sa.Integer(), nullable=True),
    sa.Column('decedent_id', sa.Integer(), nullable=True),
    sa.Column('heir_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decedent_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['grantee_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['grantor_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['heir_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('taxable_base', sa.Float(), nullable=False),
    sa.Column('gross_tax', sa.Float(), nullable=False),
    sa.Column('bonification', sa.Float(), nullable=False),
    sa.Column('net_tax', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('coefficients', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_calculation')
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('property')
    op.drop_table('people')
    # ### end Alembic commands ###
